### ISSUE TITLE
Webjars - too many open files

### ISSUE THREAD

**Issue by florianlacreuse** [igloo-project/igloo-parent#16]
@lalmeras Issue to track and discuss about webjars open files leak on development.

 * `/etc/systemd/user.conf`: `DefaultLimitNOFILE` set to `4096`
```
[flacreuse@desktop ~]$ ulimit -n
4096
```
 * Stack:
```
Exception in thread "Wicket-AsyncDataStore-PageSavingThread" java.lang.IllegalStateException: java.io.FileNotFoundException: /home/rjoly/projets/balisage-cms/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/balisage-webapp/WEB-INF/lib/httpclient-4.5.6.jar (Trop de fichiers ouverts)
    at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.getArchiveEntry(AbstractSingleArchiveResourceSet.java:101)
    at org.apache.catalina.webresources.AbstractArchiveResourceSet.getResource(AbstractArchiveResourceSet.java:256)
    at org.apache.catalina.webresources.StandardRoot.getResourceInternal(StandardRoot.java:281)
    at org.apache.catalina.webresources.Cache.getResource(Cache.java:62)
    at org.apache.catalina.webresources.StandardRoot.getResource(StandardRoot.java:216)
    at org.apache.catalina.webresources.StandardRoot.getClassLoaderResource(StandardRoot.java:225)
    at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2209)
    at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:816)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1261)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1121)
    at org.apache.log4j.spi.LoggingEvent.<init>(LoggingEvent.java:165)
    at org.apache.log4j.Category.forcedLog(Category.java:391)
    at org.apache.log4j.Category.log(Category.java:856)
    at org.slf4j.impl.Log4jLoggerAdapter.error(Log4jLoggerAdapter.java:576)
    at org.apache.wicket.pageStore.DiskDataStore$SessionEntry.getFileChannel(DiskDataStore.java:434)
    at org.apache.wicket.pageStore.DiskDataStore$SessionEntry.savePage(DiskDataStore.java:346)
    at org.apache.wicket.pageStore.DiskDataStore.storeData(DiskDataStore.java:185)
    at org.apache.wicket.pageStore.AsynchronousDataStore$PageSavingRunnable.run(AsynchronousDataStore.java:340)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: /home/rjoly/projets/balisage-cms/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/balisage-webapp/WEB-INF/lib/httpclient-4.5.6.jar (Trop de fichiers ouverts)
    at java.util.zip.ZipFile.open(Native Method)
    at java.util.zip.ZipFile.<init>(ZipFile.java:225)
    at java.util.zip.ZipFile.<init>(ZipFile.java:155)
    at java.util.jar.JarFile.<init>(JarFile.java:166)
    at java.util.jar.JarFile.<init>(JarFile.java:130)
    at org.apache.tomcat.util.compat.JreCompat.jarFileNewInstance(JreCompat.java:164)
    at org.apache.tomcat.util.compat.JreCompat.jarFileNewInstance(JreCompat.java:149)
    at org.apache.catalina.webresources.AbstractArchiveResourceSet.openJarFile(AbstractArchiveResourceSet.java:307)
    at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.getArchiveEntry(AbstractSingleArchiveResourceSet.java:97)
    ... 18 more
```

 * Bootstrap webjar seems to be involved:
```
[flacreuse@desktop ~]$ lsof -p <pid tomcat> > ulimit_files.txt
[flacreuse@desktop ~]$ grep -o "bootstrap-4.1.2.jar" ulimit_files.txt | wc -l
2462
[flacreuse@desktop ~]$ grep -o "igloo-component-wicket-bootstrap4-1.2-SNAPSHOT.jar" ulimit_files.txt | wc -l
721
```

**Comment by lalmeras** [comment]
Fixed by commit:505d33d520499fa3a7f6c1eaf2774ba013bc2546

Bug was related to lastModificationDate lookup, that lets a file handle opened. File modification lookup to update scss cache is done only in development mode. Production mode was not affected.
