### ISSUE TITLE
SCSS from jar file triggers NPE

### ISSUE THREAD

**Issue by lalmeras** [igloo-project/igloo-parent#81]
ScssServiceImpl with a jar resource fails with a NPE. For resource accessible as a classic filesystem path, there is no issue.

```
java.lang.IllegalStateException: Error generating org.iglooproject.sass.cli.ScssMain:test.scss
	at org.iglooproject.sass.cli.ScssMain.processScss(ScssMain.java:116)
	at org.iglooproject.sass.cli.ScssMain.call(ScssMain.java:81)
	at org.iglooproject.sass.cli.ScssMain.call(ScssMain.java:25)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.iglooproject.sass.cli.ScssMain.main(ScssMain.java:57)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:279)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: Error compiling jar:file:/home/lalmeras/.m2/repository/org/iglooproject/components/igloo-component-sass/5.11.0-SNAPSHOT/igloo-component-sass-5.11.0-SNAPSHOT.jar!/org/iglooproject/sass/cli/test.scss
	at org.iglooproject.sass.service.ScssServiceImpl.getCompiledDartClasspath(ScssServiceImpl.java:117)
	at org.iglooproject.sass.service.ScssServiceImpl.getCompiledStylesheet(ScssServiceImpl.java:64)
	at org.iglooproject.sass.cli.ScssMain.processScss(ScssMain.java:106)
	... 13 more
Caused by: java.lang.NullPointerException
	at java.base/java.io.File.<init>(File.java:278)
	at org.iglooproject.sass.service.ScssServiceImpl.getCompiledDartClasspath(ScssServiceImpl.java:101)
	... 15 more
One or more scss files cannot be generated. Generation failure.
```

**Comment by lalmeras** [comment]
Released in 5.10.1.
